require conf/distro/mchp-distro.conf

DISTRO = "pic64gx-rust"
DISTRO_NAME = "PIC64GX Rust Distro"
DISTROOVERRIDES = "${DISTRO}:mchp-distro"

PREFERRED_VERSION_zephyr-kernel = "4.3.99"

BB_ENV_PASSTHROUGH_ADDITIONS .= " PIC64GX_STANDALONE_FIRMWARE_PROVIDER PIC64GX_ZEPHYR_APP PIC64GX_BAREMETAL_EXAMPLE PIC64GX_BAREMETAL_SRC CARGO_HOME RUSTUP_HOME"
PIC64GX_STANDALONE_FIRMWARE_PROVIDER ?= "zephyr"
PIC64GX_ZEPHYR_APP ?= "blinky_amp"
PIC64GX_BAREMETAL_EXAMPLE ?= "test2_init_uart"
PIC64GX_BAREMETAL_SRC ?= ""
PIC64GX_BAREMETAL_BASE_REPO ?= "git://github.com/luphiax/pic64gx;protocol=https"
PIC64GX_BAREMETAL_BASE_SRCREV ?= "d73f1eb247fa288962424cdd0da6e45bcd1eb976"
PIC64GX_BAREMETAL_EXAMPLES_REPO ?= "git://github.com/luphiax/pic64gx-baremetal-examples-rust;protocol=https"
PIC64GX_BAREMETAL_EXAMPLES_SRCREV ?= "08af0e2e30f3331a65e168875c04076331dc9197"

BBMASK += " \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-bsp/u-boot/u-boot-mchp_.*\.bbappend \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/packagegroups/packagegroup-mchp-apps\.bbappend \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/pic64gx-zephyr-amp-demo/pic64gx-zephyr-amp-demo\.bb \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/pic64gx-zephyr-amp-demo/pic64gx-zephyr-amp-demo-hss\.bb \
"
