require conf/distro/mchp-distro.conf

DISTRO = "pic64gx-rust"
DISTRO_NAME = "PIC64GX Rust Distro"
DISTROOVERRIDES = "${DISTRO}:mchp-distro"

PIC64GX_ZEPHYR_APP ?= "${@os.getenv('PIC64GX_ZEPHYR_APP') or 'blinky_amp'}"

BBMASK += " \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-bsp/u-boot/u-boot-mchp_.*\.bbappend \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/packagegroups/packagegroup-mchp-apps\.bbappend \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/pic64gx-zephyr-amp-demo/pic64gx-zephyr-amp-demo\.bb \
    .*/meta-mchp/meta-mchp-pic64/dynamic-layers/zephyrcore/recipes-mchp/pic64gx-zephyr-amp-demo/pic64gx-zephyr-amp-demo-hss\.bb \
"
